import type { AppRole } from "../config/runtime";

// `Env` is generated by `wrangler types` to match bindings in wrangler.jsonc.
export type AppBindings = Env & {
  // Optional Clerk key can be injected as a runtime secret.
  CLERK_JWT_KEY?: string;
};

export type AuthContext = {
  userId: string;
  role: AppRole;
};

export type AppVariables = {
  auth: AuthContext;
};
